language: python
python:
  - 2.6
  - 2.7
install:
  - python setup.py develop
  - pip install -r requirements.txt
script:
  - cd spec; make clean all
  - cd api; make clean all
  - cd overview; make clean all
