before_install:
  - git submodule update --init --recursive
  - npm install -g less
  - npm install -g bower
  - bower install --config.interactive=false
language: python
python:
  - 2.7
install:
  - python setup.py develop
  - pip install --use-mirrors -r requirements.txt
script:
  - make clean all